package com.example.demo.pojo;

public class AddrKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column addrlist.id
     *
     * @mbg.generated Tue Jul 30 15:27:02 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column addrlist.groups
     *
     * @mbg.generated Tue Jul 30 15:27:02 CST 2019
     */
    private String groups;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column addrlist.id
     *
     * @return the value of addrlist.id
     *
     * @mbg.generated Tue Jul 30 15:27:02 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column addrlist.id
     *
     * @param id the value for addrlist.id
     *
     * @mbg.generated Tue Jul 30 15:27:02 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column addrlist.groups
     *
     * @return the value of addrlist.groups
     *
     * @mbg.generated Tue Jul 30 15:27:02 CST 2019
     */
    public String getGroups() {
        return groups;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column addrlist.groups
     *
     * @param groups the value for addrlist.groups
     *
     * @mbg.generated Tue Jul 30 15:27:02 CST 2019
     */
    public void setGroups(String groups) {
        this.groups = groups;
    }
}