package com.example.demo.pojo;

public class Addr {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column addrlist.id
	 * @mbg.generated  Wed Jul 31 19:01:45 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column addrlist.host
	 * @mbg.generated  Wed Jul 31 19:01:45 CST 2019
	 */
	private String host;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column addrlist.userid
	 * @mbg.generated  Wed Jul 31 19:01:45 CST 2019
	 */
	private String userid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column addrlist.id
	 * @return  the value of addrlist.id
	 * @mbg.generated  Wed Jul 31 19:01:45 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column addrlist.id
	 * @param id  the value for addrlist.id
	 * @mbg.generated  Wed Jul 31 19:01:45 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column addrlist.host
	 * @return  the value of addrlist.host
	 * @mbg.generated  Wed Jul 31 19:01:45 CST 2019
	 */
	public String getHost() {
		return host;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column addrlist.host
	 * @param host  the value for addrlist.host
	 * @mbg.generated  Wed Jul 31 19:01:45 CST 2019
	 */
	public void setHost(String host) {
		this.host = host;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column addrlist.userid
	 * @return  the value of addrlist.userid
	 * @mbg.generated  Wed Jul 31 19:01:45 CST 2019
	 */
	public String getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column addrlist.userid
	 * @param userid  the value for addrlist.userid
	 * @mbg.generated  Wed Jul 31 19:01:45 CST 2019
	 */
	public void setUserid(String userid) {
		this.userid = userid;
	}
}