package com.example.demo.pojo;

import java.util.List;
import java.util.Date;

public class Chat extends ChatKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column chatlist.host
	 * @mbg.generated  Wed Jul 31 16:25:52 CST 2019
	 */
	private String host;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column chatlist.time
	 * @mbg.generated  Wed Jul 31 16:25:52 CST 2019
	 */
	private Date time;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column chatlist.host
	 * @return  the value of chatlist.host
	 * @mbg.generated  Wed Jul 31 16:25:52 CST 2019
	 */
	public String getHost() {
		return host;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column chatlist.host
	 * @param host  the value for chatlist.host
	 * @mbg.generated  Wed Jul 31 16:25:52 CST 2019
	 */
	public void setHost(String host) {
		this.host = host;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column chatlist.time
	 * @return  the value of chatlist.time
	 * @mbg.generated  Wed Jul 31 16:25:52 CST 2019
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column chatlist.time
	 * @param time  the value for chatlist.time
	 * @mbg.generated  Wed Jul 31 16:25:52 CST 2019
	 */
	public void setTime(Date time) {
		this.time = time;
	}

    


}