package com.example.demo.pojo;

public class ChatKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column chatlist.id
	 * @mbg.generated  Wed Jul 31 16:25:52 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column chatlist.wechatid
	 * @mbg.generated  Wed Jul 31 16:25:52 CST 2019
	 */
	private String wechatid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column chatlist.id
	 * @return  the value of chatlist.id
	 * @mbg.generated  Wed Jul 31 16:25:52 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column chatlist.id
	 * @param id  the value for chatlist.id
	 * @mbg.generated  Wed Jul 31 16:25:52 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column chatlist.wechatid
	 * @return  the value of chatlist.wechatid
	 * @mbg.generated  Wed Jul 31 16:25:52 CST 2019
	 */
	public String getWechatid() {
		return wechatid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column chatlist.wechatid
	 * @param wechatid  the value for chatlist.wechatid
	 * @mbg.generated  Wed Jul 31 16:25:52 CST 2019
	 */
	public void setWechatid(String wechatid) {
		this.wechatid = wechatid;
	}
}