package com.example.demo.pojo;

import java.util.Date;

public class Chatroom {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column chatroomlist2.id
	 * @mbg.generated  Wed Aug 07 17:20:10 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column chatroomlist2.msg
	 * @mbg.generated  Wed Aug 07 17:20:10 CST 2019
	 */
	private String msg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column chatroomlist2.frommsg
	 * @mbg.generated  Wed Aug 07 17:20:10 CST 2019
	 */
	private String frommsg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column chatroomlist2.tomsg
	 * @mbg.generated  Wed Aug 07 17:20:10 CST 2019
	 */
	private String tomsg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column chatroomlist2.time
	 * @mbg.generated  Wed Aug 07 17:20:10 CST 2019
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column chatroomlist2.text
	 * @mbg.generated  Wed Aug 07 17:20:10 CST 2019
	 */
	private Integer text;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column chatroomlist2.unread
	 * @mbg.generated  Wed Aug 07 17:20:10 CST 2019
	 */
	private Integer unread;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column chatroomlist2.id
	 * @return  the value of chatroomlist2.id
	 * @mbg.generated  Wed Aug 07 17:20:10 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column chatroomlist2.id
	 * @param id  the value for chatroomlist2.id
	 * @mbg.generated  Wed Aug 07 17:20:10 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column chatroomlist2.msg
	 * @return  the value of chatroomlist2.msg
	 * @mbg.generated  Wed Aug 07 17:20:10 CST 2019
	 */
	public String getMsg() {
		return msg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column chatroomlist2.msg
	 * @param msg  the value for chatroomlist2.msg
	 * @mbg.generated  Wed Aug 07 17:20:10 CST 2019
	 */
	public void setMsg(String msg) {
		this.msg = msg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column chatroomlist2.frommsg
	 * @return  the value of chatroomlist2.frommsg
	 * @mbg.generated  Wed Aug 07 17:20:10 CST 2019
	 */
	public String getFrommsg() {
		return frommsg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column chatroomlist2.frommsg
	 * @param frommsg  the value for chatroomlist2.frommsg
	 * @mbg.generated  Wed Aug 07 17:20:10 CST 2019
	 */
	public void setFrommsg(String frommsg) {
		this.frommsg = frommsg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column chatroomlist2.tomsg
	 * @return  the value of chatroomlist2.tomsg
	 * @mbg.generated  Wed Aug 07 17:20:10 CST 2019
	 */
	public String getTomsg() {
		return tomsg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column chatroomlist2.tomsg
	 * @param tomsg  the value for chatroomlist2.tomsg
	 * @mbg.generated  Wed Aug 07 17:20:10 CST 2019
	 */
	public void setTomsg(String tomsg) {
		this.tomsg = tomsg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column chatroomlist2.time
	 * @return  the value of chatroomlist2.time
	 * @mbg.generated  Wed Aug 07 17:20:10 CST 2019
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column chatroomlist2.time
	 * @param time  the value for chatroomlist2.time
	 * @mbg.generated  Wed Aug 07 17:20:10 CST 2019
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column chatroomlist2.text
	 * @return  the value of chatroomlist2.text
	 * @mbg.generated  Wed Aug 07 17:20:10 CST 2019
	 */
	public Integer getText() {
		return text;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column chatroomlist2.text
	 * @param text  the value for chatroomlist2.text
	 * @mbg.generated  Wed Aug 07 17:20:10 CST 2019
	 */
	public void setText(Integer text) {
		this.text = text;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column chatroomlist2.unread
	 * @return  the value of chatroomlist2.unread
	 * @mbg.generated  Wed Aug 07 17:20:10 CST 2019
	 */
	public Integer getUnread() {
		return unread;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column chatroomlist2.unread
	 * @param unread  the value for chatroomlist2.unread
	 * @mbg.generated  Wed Aug 07 17:20:10 CST 2019
	 */
	public void setUnread(Integer unread) {
		this.unread = unread;
	}
}