package com.example.demo.pojo;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;

public class ChatroomExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table chatroomlist2
	 * @mbg.generated  Thu Aug 29 10:54:04 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table chatroomlist2
	 * @mbg.generated  Thu Aug 29 10:54:04 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table chatroomlist2
	 * @mbg.generated  Thu Aug 29 10:54:04 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chatroomlist2
	 * @mbg.generated  Thu Aug 29 10:54:04 CST 2019
	 */
	public ChatroomExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chatroomlist2
	 * @mbg.generated  Thu Aug 29 10:54:04 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chatroomlist2
	 * @mbg.generated  Thu Aug 29 10:54:04 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chatroomlist2
	 * @mbg.generated  Thu Aug 29 10:54:04 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chatroomlist2
	 * @mbg.generated  Thu Aug 29 10:54:04 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chatroomlist2
	 * @mbg.generated  Thu Aug 29 10:54:04 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chatroomlist2
	 * @mbg.generated  Thu Aug 29 10:54:04 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chatroomlist2
	 * @mbg.generated  Thu Aug 29 10:54:04 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chatroomlist2
	 * @mbg.generated  Thu Aug 29 10:54:04 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chatroomlist2
	 * @mbg.generated  Thu Aug 29 10:54:04 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chatroomlist2
	 * @mbg.generated  Thu Aug 29 10:54:04 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table chatroomlist2
	 * @mbg.generated  Thu Aug 29 10:54:04 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andMsgIsNull() {
			addCriterion("msg is null");
			return (Criteria) this;
		}

		public Criteria andMsgIsNotNull() {
			addCriterion("msg is not null");
			return (Criteria) this;
		}

		public Criteria andMsgEqualTo(String value) {
			addCriterion("msg =", value, "msg");
			return (Criteria) this;
		}

		public Criteria andMsgNotEqualTo(String value) {
			addCriterion("msg <>", value, "msg");
			return (Criteria) this;
		}

		public Criteria andMsgGreaterThan(String value) {
			addCriterion("msg >", value, "msg");
			return (Criteria) this;
		}

		public Criteria andMsgGreaterThanOrEqualTo(String value) {
			addCriterion("msg >=", value, "msg");
			return (Criteria) this;
		}

		public Criteria andMsgLessThan(String value) {
			addCriterion("msg <", value, "msg");
			return (Criteria) this;
		}

		public Criteria andMsgLessThanOrEqualTo(String value) {
			addCriterion("msg <=", value, "msg");
			return (Criteria) this;
		}

		public Criteria andMsgLike(String value) {
			addCriterion("msg like", value, "msg");
			return (Criteria) this;
		}

		public Criteria andMsgNotLike(String value) {
			addCriterion("msg not like", value, "msg");
			return (Criteria) this;
		}

		public Criteria andMsgIn(List<String> values) {
			addCriterion("msg in", values, "msg");
			return (Criteria) this;
		}

		public Criteria andMsgNotIn(List<String> values) {
			addCriterion("msg not in", values, "msg");
			return (Criteria) this;
		}

		public Criteria andMsgBetween(String value1, String value2) {
			addCriterion("msg between", value1, value2, "msg");
			return (Criteria) this;
		}

		public Criteria andMsgNotBetween(String value1, String value2) {
			addCriterion("msg not between", value1, value2, "msg");
			return (Criteria) this;
		}

		public Criteria andFrommsgIsNull() {
			addCriterion("frommsg is null");
			return (Criteria) this;
		}

		public Criteria andFrommsgIsNotNull() {
			addCriterion("frommsg is not null");
			return (Criteria) this;
		}

		public Criteria andFrommsgEqualTo(String value) {
			addCriterion("frommsg =", value, "frommsg");
			return (Criteria) this;
		}

		public Criteria andFrommsgNotEqualTo(String value) {
			addCriterion("frommsg <>", value, "frommsg");
			return (Criteria) this;
		}

		public Criteria andFrommsgGreaterThan(String value) {
			addCriterion("frommsg >", value, "frommsg");
			return (Criteria) this;
		}

		public Criteria andFrommsgGreaterThanOrEqualTo(String value) {
			addCriterion("frommsg >=", value, "frommsg");
			return (Criteria) this;
		}

		public Criteria andFrommsgLessThan(String value) {
			addCriterion("frommsg <", value, "frommsg");
			return (Criteria) this;
		}

		public Criteria andFrommsgLessThanOrEqualTo(String value) {
			addCriterion("frommsg <=", value, "frommsg");
			return (Criteria) this;
		}

		public Criteria andFrommsgLike(String value) {
			addCriterion("frommsg like", value, "frommsg");
			return (Criteria) this;
		}

		public Criteria andFrommsgNotLike(String value) {
			addCriterion("frommsg not like", value, "frommsg");
			return (Criteria) this;
		}

		public Criteria andFrommsgIn(List<String> values) {
			addCriterion("frommsg in", values, "frommsg");
			return (Criteria) this;
		}

		public Criteria andFrommsgNotIn(List<String> values) {
			addCriterion("frommsg not in", values, "frommsg");
			return (Criteria) this;
		}

		public Criteria andFrommsgBetween(String value1, String value2) {
			addCriterion("frommsg between", value1, value2, "frommsg");
			return (Criteria) this;
		}

		public Criteria andFrommsgNotBetween(String value1, String value2) {
			addCriterion("frommsg not between", value1, value2, "frommsg");
			return (Criteria) this;
		}

		public Criteria andTomsgIsNull() {
			addCriterion("tomsg is null");
			return (Criteria) this;
		}

		public Criteria andTomsgIsNotNull() {
			addCriterion("tomsg is not null");
			return (Criteria) this;
		}

		public Criteria andTomsgEqualTo(String value) {
			addCriterion("tomsg =", value, "tomsg");
			return (Criteria) this;
		}

		public Criteria andTomsgNotEqualTo(String value) {
			addCriterion("tomsg <>", value, "tomsg");
			return (Criteria) this;
		}

		public Criteria andTomsgGreaterThan(String value) {
			addCriterion("tomsg >", value, "tomsg");
			return (Criteria) this;
		}

		public Criteria andTomsgGreaterThanOrEqualTo(String value) {
			addCriterion("tomsg >=", value, "tomsg");
			return (Criteria) this;
		}

		public Criteria andTomsgLessThan(String value) {
			addCriterion("tomsg <", value, "tomsg");
			return (Criteria) this;
		}

		public Criteria andTomsgLessThanOrEqualTo(String value) {
			addCriterion("tomsg <=", value, "tomsg");
			return (Criteria) this;
		}

		public Criteria andTomsgLike(String value) {
			addCriterion("tomsg like", value, "tomsg");
			return (Criteria) this;
		}

		public Criteria andTomsgNotLike(String value) {
			addCriterion("tomsg not like", value, "tomsg");
			return (Criteria) this;
		}

		public Criteria andTomsgIn(List<String> values) {
			addCriterion("tomsg in", values, "tomsg");
			return (Criteria) this;
		}

		public Criteria andTomsgNotIn(List<String> values) {
			addCriterion("tomsg not in", values, "tomsg");
			return (Criteria) this;
		}

		public Criteria andTomsgBetween(String value1, String value2) {
			addCriterion("tomsg between", value1, value2, "tomsg");
			return (Criteria) this;
		}

		public Criteria andTomsgNotBetween(String value1, String value2) {
			addCriterion("tomsg not between", value1, value2, "tomsg");
			return (Criteria) this;
		}

		public Criteria andTimeIsNull() {
			addCriterion("time is null");
			return (Criteria) this;
		}

		public Criteria andTimeIsNotNull() {
			addCriterion("time is not null");
			return (Criteria) this;
		}

		public Criteria andTimeEqualTo(Date value) {
			addCriterion("time =", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotEqualTo(Date value) {
			addCriterion("time <>", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeGreaterThan(Date value) {
			addCriterion("time >", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("time >=", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeLessThan(Date value) {
			addCriterion("time <", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeLessThanOrEqualTo(Date value) {
			addCriterion("time <=", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeIn(List<Date> values) {
			addCriterion("time in", values, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotIn(List<Date> values) {
			addCriterion("time not in", values, "time");
			return (Criteria) this;
		}

		public Criteria andTimeBetween(Date value1, Date value2) {
			addCriterion("time between", value1, value2, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotBetween(Date value1, Date value2) {
			addCriterion("time not between", value1, value2, "time");
			return (Criteria) this;
		}

		public Criteria andTextIsNull() {
			addCriterion("text is null");
			return (Criteria) this;
		}

		public Criteria andTextIsNotNull() {
			addCriterion("text is not null");
			return (Criteria) this;
		}

		public Criteria andTextEqualTo(Integer value) {
			addCriterion("text =", value, "text");
			return (Criteria) this;
		}

		public Criteria andTextNotEqualTo(Integer value) {
			addCriterion("text <>", value, "text");
			return (Criteria) this;
		}

		public Criteria andTextGreaterThan(Integer value) {
			addCriterion("text >", value, "text");
			return (Criteria) this;
		}

		public Criteria andTextGreaterThanOrEqualTo(Integer value) {
			addCriterion("text >=", value, "text");
			return (Criteria) this;
		}

		public Criteria andTextLessThan(Integer value) {
			addCriterion("text <", value, "text");
			return (Criteria) this;
		}

		public Criteria andTextLessThanOrEqualTo(Integer value) {
			addCriterion("text <=", value, "text");
			return (Criteria) this;
		}

		public Criteria andTextIn(List<Integer> values) {
			addCriterion("text in", values, "text");
			return (Criteria) this;
		}

		public Criteria andTextNotIn(List<Integer> values) {
			addCriterion("text not in", values, "text");
			return (Criteria) this;
		}

		public Criteria andTextBetween(Integer value1, Integer value2) {
			addCriterion("text between", value1, value2, "text");
			return (Criteria) this;
		}

		public Criteria andTextNotBetween(Integer value1, Integer value2) {
			addCriterion("text not between", value1, value2, "text");
			return (Criteria) this;
		}

		public Criteria andUnreadIsNull() {
			addCriterion("unread is null");
			return (Criteria) this;
		}

		public Criteria andUnreadIsNotNull() {
			addCriterion("unread is not null");
			return (Criteria) this;
		}

		public Criteria andUnreadEqualTo(Integer value) {
			addCriterion("unread =", value, "unread");
			return (Criteria) this;
		}

		public Criteria andUnreadNotEqualTo(Integer value) {
			addCriterion("unread <>", value, "unread");
			return (Criteria) this;
		}

		public Criteria andUnreadGreaterThan(Integer value) {
			addCriterion("unread >", value, "unread");
			return (Criteria) this;
		}

		public Criteria andUnreadGreaterThanOrEqualTo(Integer value) {
			addCriterion("unread >=", value, "unread");
			return (Criteria) this;
		}

		public Criteria andUnreadLessThan(Integer value) {
			addCriterion("unread <", value, "unread");
			return (Criteria) this;
		}

		public Criteria andUnreadLessThanOrEqualTo(Integer value) {
			addCriterion("unread <=", value, "unread");
			return (Criteria) this;
		}

		public Criteria andUnreadIn(List<Integer> values) {
			addCriterion("unread in", values, "unread");
			return (Criteria) this;
		}

		public Criteria andUnreadNotIn(List<Integer> values) {
			addCriterion("unread not in", values, "unread");
			return (Criteria) this;
		}

		public Criteria andUnreadBetween(Integer value1, Integer value2) {
			addCriterion("unread between", value1, value2, "unread");
			return (Criteria) this;
		}

		public Criteria andUnreadNotBetween(Integer value1, Integer value2) {
			addCriterion("unread not between", value1, value2, "unread");
			return (Criteria) this;
		}

		public Criteria andIsgroupIsNull() {
			addCriterion("isgroup is null");
			return (Criteria) this;
		}

		public Criteria andIsgroupIsNotNull() {
			addCriterion("isgroup is not null");
			return (Criteria) this;
		}

		public Criteria andIsgroupEqualTo(Integer value) {
			addCriterion("isgroup =", value, "isgroup");
			return (Criteria) this;
		}

		public Criteria andIsgroupNotEqualTo(Integer value) {
			addCriterion("isgroup <>", value, "isgroup");
			return (Criteria) this;
		}

		public Criteria andIsgroupGreaterThan(Integer value) {
			addCriterion("isgroup >", value, "isgroup");
			return (Criteria) this;
		}

		public Criteria andIsgroupGreaterThanOrEqualTo(Integer value) {
			addCriterion("isgroup >=", value, "isgroup");
			return (Criteria) this;
		}

		public Criteria andIsgroupLessThan(Integer value) {
			addCriterion("isgroup <", value, "isgroup");
			return (Criteria) this;
		}

		public Criteria andIsgroupLessThanOrEqualTo(Integer value) {
			addCriterion("isgroup <=", value, "isgroup");
			return (Criteria) this;
		}

		public Criteria andIsgroupIn(List<Integer> values) {
			addCriterion("isgroup in", values, "isgroup");
			return (Criteria) this;
		}

		public Criteria andIsgroupNotIn(List<Integer> values) {
			addCriterion("isgroup not in", values, "isgroup");
			return (Criteria) this;
		}

		public Criteria andIsgroupBetween(Integer value1, Integer value2) {
			addCriterion("isgroup between", value1, value2, "isgroup");
			return (Criteria) this;
		}

		public Criteria andIsgroupNotBetween(Integer value1, Integer value2) {
			addCriterion("isgroup not between", value1, value2, "isgroup");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table chatroomlist2
	 * @mbg.generated  Thu Aug 29 10:54:04 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table chatroomlist
     *
     * @mbg.generated do_not_delete_during_merge Fri Jul 26 10:17:51 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}