package com.example.demo.pojo;

import java.util.Date;

public class ConcatTable  {
	
	private Short id;

	private String wechatId;

	private String loginName;

	private String avatar;

	private Integer datacount;
	
	private Date time;
	
	private String msg;
	
	private Integer text;
	
	private String frommsg1;
	
	private Integer isgroup;
	
	
	
	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}
	
	public String getLoginName() {
		return loginName;
	}
	
	public String getMsg() {
		return msg;
	}

	public void setMsg(String msg) {
		this.msg = msg;
	}
	
	public String getAvatar() {
		return avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}
	
	public Short getId() {
		return id;
	}

	public void setId(Short id) {
		this.id = id;
	}
	
	public String getWechatId() {
		return wechatId;
	}

	public void setWechatId(String wechatId) {
		this.wechatId = wechatId;
	}
	
	public Date getTime() {
		return time;
	}

	public void setTime(Date time) {
		this.time = time;
	}
	
	public Integer getDatacount() {
		return datacount;
	}
	
	public Integer getText() {
		return text;
	}

	public void setText(Integer text) {
		this.text = text;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column chatroomlist2.unread
	 * @param unread  the value for chatroomlist2.unread
	 * @mbg.generated  Wed Aug 07 17:20:10 CST 2019
	 */
	public void setDatacount(Integer datacount) {
		this.datacount = datacount;
	}
	
	public Integer getIsgroup() {
		return isgroup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column chatroomlist2.isgroup
	 * @param isgroup  the value for chatroomlist2.isgroup
	 * @mbg.generated  Thu Aug 29 10:54:04 CST 2019
	 */
	public void setIsgroup(Integer isgroup) {
		this.isgroup = isgroup;
	}
	
	public String getFrommsg() {
		return frommsg1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column chatroomlist2.frommsg
	 * @param frommsg  the value for chatroomlist2.frommsg
	 * @mbg.generated  Thu Aug 29 10:54:04 CST 2019
	 */
	public void setFrommsg(String frommsg) {
		this.frommsg1 = frommsg;
	}




	

}