package com.example.demo.pojo;

public class Grouplist {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grouplist.id1
     *
     * @mbg.generated Thu Aug 29 16:20:34 CST 2019
     */
    private Integer id1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grouplist.GroupName
     *
     * @mbg.generated Thu Aug 29 16:20:34 CST 2019
     */
    private String groupname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grouplist.member
     *
     * @mbg.generated Thu Aug 29 16:20:34 CST 2019
     */
    private String member;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grouplist.GroupId
     *
     * @mbg.generated Thu Aug 29 16:20:34 CST 2019
     */
    private String groupid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grouplist.Header
     *
     * @mbg.generated Thu Aug 29 16:20:34 CST 2019
     */
    private String header;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grouplist.id1
     *
     * @return the value of grouplist.id1
     *
     * @mbg.generated Thu Aug 29 16:20:34 CST 2019
     */
    public Integer getId1() {
        return id1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grouplist.id1
     *
     * @param id1 the value for grouplist.id1
     *
     * @mbg.generated Thu Aug 29 16:20:34 CST 2019
     */
    public void setId1(Integer id1) {
        this.id1 = id1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grouplist.GroupName
     *
     * @return the value of grouplist.GroupName
     *
     * @mbg.generated Thu Aug 29 16:20:34 CST 2019
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grouplist.GroupName
     *
     * @param groupname the value for grouplist.GroupName
     *
     * @mbg.generated Thu Aug 29 16:20:34 CST 2019
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grouplist.member
     *
     * @return the value of grouplist.member
     *
     * @mbg.generated Thu Aug 29 16:20:34 CST 2019
     */
    public String getMember() {
        return member;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grouplist.member
     *
     * @param member the value for grouplist.member
     *
     * @mbg.generated Thu Aug 29 16:20:34 CST 2019
     */
    public void setMember(String member) {
        this.member = member;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grouplist.GroupId
     *
     * @return the value of grouplist.GroupId
     *
     * @mbg.generated Thu Aug 29 16:20:34 CST 2019
     */
    public String getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grouplist.GroupId
     *
     * @param groupid the value for grouplist.GroupId
     *
     * @mbg.generated Thu Aug 29 16:20:34 CST 2019
     */
    public void setGroupid(String groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grouplist.Header
     *
     * @return the value of grouplist.Header
     *
     * @mbg.generated Thu Aug 29 16:20:34 CST 2019
     */
    public String getHeader() {
        return header;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grouplist.Header
     *
     * @param header the value for grouplist.Header
     *
     * @mbg.generated Thu Aug 29 16:20:34 CST 2019
     */
    public void setHeader(String header) {
        this.header = header;
    }
}