package com.example.demo.pojo;

import java.util.Date;

public class Mom {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column momentslist.id
	 * @mbg.generated  Wed Jul 31 14:11:23 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column momentslist.wechatid
	 * @mbg.generated  Wed Jul 31 14:11:23 CST 2019
	 */
	private String wechatid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column momentslist.context
	 * @mbg.generated  Wed Jul 31 14:11:23 CST 2019
	 */
	private String context;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column momentslist.album
	 * @mbg.generated  Wed Jul 31 14:11:23 CST 2019
	 */
	private String album;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column momentslist.host
	 * @mbg.generated  Wed Jul 31 14:11:23 CST 2019
	 */
	private String host;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column momentslist.time
	 * @mbg.generated  Wed Jul 31 14:11:23 CST 2019
	 */
	private Date time;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column momentslist.id
	 * @return  the value of momentslist.id
	 * @mbg.generated  Wed Jul 31 14:11:23 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column momentslist.id
	 * @param id  the value for momentslist.id
	 * @mbg.generated  Wed Jul 31 14:11:23 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column momentslist.wechatid
	 * @return  the value of momentslist.wechatid
	 * @mbg.generated  Wed Jul 31 14:11:23 CST 2019
	 */
	public String getWechatid() {
		return wechatid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column momentslist.wechatid
	 * @param wechatid  the value for momentslist.wechatid
	 * @mbg.generated  Wed Jul 31 14:11:23 CST 2019
	 */
	public void setWechatid(String wechatid) {
		this.wechatid = wechatid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column momentslist.context
	 * @return  the value of momentslist.context
	 * @mbg.generated  Wed Jul 31 14:11:23 CST 2019
	 */
	public String getContext() {
		return context;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column momentslist.context
	 * @param context  the value for momentslist.context
	 * @mbg.generated  Wed Jul 31 14:11:23 CST 2019
	 */
	public void setContext(String context) {
		this.context = context;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column momentslist.album
	 * @return  the value of momentslist.album
	 * @mbg.generated  Wed Jul 31 14:11:23 CST 2019
	 */
	public String getAlbum() {
		return album;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column momentslist.album
	 * @param album  the value for momentslist.album
	 * @mbg.generated  Wed Jul 31 14:11:23 CST 2019
	 */
	public void setAlbum(String album) {
		this.album = album;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column momentslist.host
	 * @return  the value of momentslist.host
	 * @mbg.generated  Wed Jul 31 14:11:23 CST 2019
	 */
	public String getHost() {
		return host;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column momentslist.host
	 * @param host  the value for momentslist.host
	 * @mbg.generated  Wed Jul 31 14:11:23 CST 2019
	 */
	public void setHost(String host) {
		this.host = host;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column momentslist.time
	 * @return  the value of momentslist.time
	 * @mbg.generated  Wed Jul 31 14:11:23 CST 2019
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column momentslist.time
	 * @param time  the value for momentslist.time
	 * @mbg.generated  Wed Jul 31 14:11:23 CST 2019
	 */
	public void setTime(Date time) {
		this.time = time;
	}
}