package com.example.demo.pojo;

public class UserKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
	 * @mbg.generated  Wed Jul 31 17:04:55 CST 2019
	 */
	private Short id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.wechat_id
	 * @mbg.generated  Wed Jul 31 17:04:55 CST 2019
	 */
	private String wechatId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
	 * @return  the value of user.id
	 * @mbg.generated  Wed Jul 31 17:04:55 CST 2019
	 */
	public Short getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
	 * @param id  the value for user.id
	 * @mbg.generated  Wed Jul 31 17:04:55 CST 2019
	 */
	public void setId(Short id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.wechat_id
	 * @return  the value of user.wechat_id
	 * @mbg.generated  Wed Jul 31 17:04:55 CST 2019
	 */
	public String getWechatId() {
		return wechatId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.wechat_id
	 * @param wechatId  the value for user.wechat_id
	 * @mbg.generated  Wed Jul 31 17:04:55 CST 2019
	 */
	public void setWechatId(String wechatId) {
		this.wechatId = wechatId;
	}
}