package com.example.demo.pojo;

import java.util.List;

public class User  {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
	 * @mbg.generated  Wed Jul 31 17:04:55 CST 2019
	 */
	private Short id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.wechat_id
	 * @mbg.generated  Wed Jul 31 17:04:55 CST 2019
	 */
	private String wechatId;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.login_name
	 * @mbg.generated  Wed Jul 31 17:04:55 CST 2019
	 */
	private String loginName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
	 * @mbg.generated  Wed Jul 31 17:04:55 CST 2019
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.avatar
	 * @mbg.generated  Wed Jul 31 17:04:55 CST 2019
	 */
	private String avatar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.groups
	 * @mbg.generated  Wed Jul 31 17:04:55 CST 2019
	 */
	private String groups;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.location
	 * @mbg.generated  Wed Jul 31 17:04:55 CST 2019
	 */
	private String location;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.login_name
	 * @return  the value of user.login_name
	 * @mbg.generated  Wed Jul 31 17:04:55 CST 2019
	 */
	public String getLoginName() {
		return loginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.login_name
	 * @param loginName  the value for user.login_name
	 * @mbg.generated  Wed Jul 31 17:04:55 CST 2019
	 */
	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbg.generated  Wed Jul 31 17:04:55 CST 2019
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @mbg.generated  Wed Jul 31 17:04:55 CST 2019
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.avatar
	 * @return  the value of user.avatar
	 * @mbg.generated  Wed Jul 31 17:04:55 CST 2019
	 */
	public String getAvatar() {
		return avatar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.avatar
	 * @param avatar  the value for user.avatar
	 * @mbg.generated  Wed Jul 31 17:04:55 CST 2019
	 */
	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.groups
	 * @return  the value of user.groups
	 * @mbg.generated  Wed Jul 31 17:04:55 CST 2019
	 */
	public String getGroups() {
		return groups;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.groups
	 * @param groups  the value for user.groups
	 * @mbg.generated  Wed Jul 31 17:04:55 CST 2019
	 */
	public void setGroups(String groups) {
		this.groups = groups;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.location
	 * @return  the value of user.location
	 * @mbg.generated  Wed Jul 31 17:04:55 CST 2019
	 */
	public String getLocation() {
		return location;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.location
	 * @param location  the value for user.location
	 * @mbg.generated  Wed Jul 31 17:04:55 CST 2019
	 */
	public void setLocation(String location) {
		this.location = location;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
	 * @return  the value of user.id
	 * @mbg.generated  Wed Jul 31 17:04:55 CST 2019
	 */
	public Short getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
	 * @param id  the value for user.id
	 * @mbg.generated  Wed Jul 31 17:04:55 CST 2019
	 */
	public void setId(Short id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.wechat_id
	 * @return  the value of user.wechat_id
	 * @mbg.generated  Wed Jul 31 17:04:55 CST 2019
	 */
	public String getWechatId() {
		return wechatId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.wechat_id
	 * @param wechatId  the value for user.wechat_id
	 * @mbg.generated  Wed Jul 31 17:04:55 CST 2019
	 */
	public void setWechatId(String wechatId) {
		this.wechatId = wechatId;
	}

	

}