server:
  port: 8069

spring:
  profiles:
    active: dev
#  jackson:
#    time-zone: GMT+8
    
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/userinfo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
    type: org.apache.tomcat.jdbc.pool.DataSource
    tomcat:
      initSQL: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci

    

mybatis:
  mapperLocations: classpath:com/example/demo/mapping/*.xml
#  configLocation: classpath:mybatis-config.xml
  typeAliasesPackage: com.example.demo.pojo


    
