package com.example.demo.dao;

import com.example.demo.pojo.Addr;
import com.example.demo.pojo.AddrExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.example.demo.pojo.AddrKey;
import com.example.demo.pojo.ConcatMom;

public interface AddrMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table addrlist
	 * @mbg.generated  Wed Jul 31 19:01:45 CST 2019
	 */
	long countByExample(AddrExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table addrlist
	 * @mbg.generated  Wed Jul 31 19:01:45 CST 2019
	 */
	int deleteByExample(AddrExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table addrlist
	 * @mbg.generated  Wed Jul 31 19:01:45 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table addrlist
	 * @mbg.generated  Wed Jul 31 19:01:45 CST 2019
	 */
	int insert(Addr record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table addrlist
	 * @mbg.generated  Wed Jul 31 19:01:45 CST 2019
	 */
	int insertSelective(Addr record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table addrlist
	 * @mbg.generated  Wed Jul 31 19:01:45 CST 2019
	 */
	List<Addr> selectByExample(AddrExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table addrlist
	 * @mbg.generated  Wed Jul 31 19:01:45 CST 2019
	 */
	Addr selectByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table addrlist
	 * @mbg.generated  Wed Jul 31 19:01:45 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Addr record, @Param("example") AddrExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table addrlist
	 * @mbg.generated  Wed Jul 31 19:01:45 CST 2019
	 */
	int updateByExample(@Param("record") Addr record, @Param("example") AddrExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table addrlist
	 * @mbg.generated  Wed Jul 31 19:01:45 CST 2019
	 */
	int updateByPrimaryKeySelective(Addr record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table addrlist
	 * @mbg.generated  Wed Jul 31 19:01:45 CST 2019
	 */
	int updateByPrimaryKey(Addr record);
	List<Addr> selectAlladdr();
    List<Addr> selectAllgroups();
    List<ConcatMom> selectMomentsList(String userid);
    int insertNewFriend(String id1, String id2);
}