package com.example.demo.dao;

//import com.alibaba.druid.sql.visitor.functions.Concat;
import com.example.demo.pojo.Chat;
import com.example.demo.pojo.Chatroom;
import com.example.demo.pojo.ChatroomExample;
import com.example.demo.pojo.User;
import com.example.demo.pojo.ConcatTable;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChatroomMapper {
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chatroomlist2
	 * @mbg.generated  Wed Aug 07 17:20:10 CST 2019
	 */
	long countByExample(ChatroomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chatroomlist2
	 * @mbg.generated  Wed Aug 07 17:20:10 CST 2019
	 */
	int deleteByExample(ChatroomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chatroomlist2
	 * @mbg.generated  Wed Aug 07 17:20:10 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chatroomlist2
	 * @mbg.generated  Wed Aug 07 17:20:10 CST 2019
	 */
	int insert(Chatroom record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chatroomlist2
	 * @mbg.generated  Wed Aug 07 17:20:10 CST 2019
	 */
	int insertSelective(Chatroom record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chatroomlist2
	 * @mbg.generated  Wed Aug 07 17:20:10 CST 2019
	 */
	List<Chatroom> selectByExample(ChatroomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chatroomlist2
	 * @mbg.generated  Wed Aug 07 17:20:10 CST 2019
	 */
	Chatroom selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chatroomlist2
	 * @mbg.generated  Wed Aug 07 17:20:10 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Chatroom record, @Param("example") ChatroomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chatroomlist2
	 * @mbg.generated  Wed Aug 07 17:20:10 CST 2019
	 */
	int updateByExample(@Param("record") Chatroom record, @Param("example") ChatroomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chatroomlist2
	 * @mbg.generated  Wed Aug 07 17:20:10 CST 2019
	 */
	int updateByPrimaryKeySelective(Chatroom record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chatroomlist2
	 * @mbg.generated  Wed Aug 07 17:20:10 CST 2019
	 */
	int updateByPrimaryKey(Chatroom record);

	List<Chatroom> selectByWechatName(String wechatName);
	
	List<Chatroom> selectByWechatId(String wechatid, String wechathost);
	List<Chatroom> selectAllByHost(String host);
	List<ConcatTable> selectUnreadNum(String host);
	int insertNewMsg(Chatroom chatroom);
	int setUnreadNum(@Param("wechatid") String wechatid, @Param("wechathost") String wechathost, @Param("unread") int unread);
}