package com.example.demo.dao;

import com.example.demo.pojo.Grouplist;
import com.example.demo.pojo.GrouplistExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GrouplistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grouplist
     *
     * @mbg.generated Thu Aug 29 16:20:34 CST 2019
     */
    long countByExample(GrouplistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grouplist
     *
     * @mbg.generated Thu Aug 29 16:20:34 CST 2019
     */
    int deleteByExample(GrouplistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grouplist
     *
     * @mbg.generated Thu Aug 29 16:20:34 CST 2019
     */
    int deleteByPrimaryKey(Integer id1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grouplist
     *
     * @mbg.generated Thu Aug 29 16:20:34 CST 2019
     */
    int insert(Grouplist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grouplist
     *
     * @mbg.generated Thu Aug 29 16:20:34 CST 2019
     */
    int insertSelective(Grouplist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grouplist
     *
     * @mbg.generated Thu Aug 29 16:20:34 CST 2019
     */
    List<Grouplist> selectByExample(GrouplistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grouplist
     *
     * @mbg.generated Thu Aug 29 16:20:34 CST 2019
     */
    Grouplist selectByPrimaryKey(Integer id1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grouplist
     *
     * @mbg.generated Thu Aug 29 16:20:34 CST 2019
     */
    int updateByExampleSelective(@Param("record") Grouplist record, @Param("example") GrouplistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grouplist
     *
     * @mbg.generated Thu Aug 29 16:20:34 CST 2019
     */
    int updateByExample(@Param("record") Grouplist record, @Param("example") GrouplistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grouplist
     *
     * @mbg.generated Thu Aug 29 16:20:34 CST 2019
     */
    int updateByPrimaryKeySelective(Grouplist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grouplist
     *
     * @mbg.generated Thu Aug 29 16:20:34 CST 2019
     */
    int updateByPrimaryKey(Grouplist record);
}