package com.example.demo.dao;

import com.example.demo.pojo.Mom;
import com.example.demo.pojo.MomExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MomMapper {
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table momentslist
	 * @mbg.generated  Wed Jul 31 14:11:23 CST 2019
	 */
	long countByExample(MomExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table momentslist
	 * @mbg.generated  Wed Jul 31 14:11:23 CST 2019
	 */
	int deleteByExample(MomExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table momentslist
	 * @mbg.generated  Wed Jul 31 14:11:23 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table momentslist
	 * @mbg.generated  Wed Jul 31 14:11:23 CST 2019
	 */
	int insert(Mom record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table momentslist
	 * @mbg.generated  Wed Jul 31 14:11:23 CST 2019
	 */
	int insertSelective(Mom record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table momentslist
	 * @mbg.generated  Wed Jul 31 14:11:23 CST 2019
	 */
	List<Mom> selectByExample(MomExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table momentslist
	 * @mbg.generated  Wed Jul 31 14:11:23 CST 2019
	 */
	Mom selectByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table momentslist
	 * @mbg.generated  Wed Jul 31 14:11:23 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Mom record, @Param("example") MomExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table momentslist
	 * @mbg.generated  Wed Jul 31 14:11:23 CST 2019
	 */
	int updateByExample(@Param("record") Mom record, @Param("example") MomExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table momentslist
	 * @mbg.generated  Wed Jul 31 14:11:23 CST 2019
	 */
	int updateByPrimaryKeySelective(Mom record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table momentslist
	 * @mbg.generated  Wed Jul 31 14:11:23 CST 2019
	 */
	int updateByPrimaryKey(Mom record);
	List<Mom> selectAllMoments();
	List<Mom> selectAllMomentsByHost(String host);
}