
package com.example.demo.dao;
 
import com.example.demo.pojo.Addr;
import com.example.demo.pojo.Chat;
import com.example.demo.pojo.Mom;
import com.example.demo.pojo.User;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Repository;
import com.example.demo.pojo.UserExample;
import java.util.List;
import com.example.demo.pojo.UserKey;



@Mapper
public interface UserMapper {
	 /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Wed Jul 31 17:04:55 CST 2019
	 */
	long countByExample(UserExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Wed Jul 31 17:04:55 CST 2019
	 */
	int deleteByExample(UserExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Wed Jul 31 17:04:55 CST 2019
	 */
	int deleteByPrimaryKey(UserKey key);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Wed Jul 31 17:04:55 CST 2019
	 */
	int insert(User record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Wed Jul 31 17:04:55 CST 2019
	 */
	int insertSelective(User record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Wed Jul 31 17:04:55 CST 2019
	 */
	List<User> selectByExample(UserExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Wed Jul 31 17:04:55 CST 2019
	 */
	User selectByPrimaryKey(UserKey key);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Wed Jul 31 17:04:55 CST 2019
	 */
	int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Wed Jul 31 17:04:55 CST 2019
	 */
	int updateByExample(@Param("record") User record, @Param("example") UserExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Wed Jul 31 17:04:55 CST 2019
	 */
	int updateByPrimaryKeySelective(User record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Wed Jul 31 17:04:55 CST 2019
	 */
	int updateByPrimaryKey(User record);
	User selectByNamePwd(@Param("loginName") String loginName, @Param("pwd") String pwd);  
	User selectByUserId(String loginName);
	User selectByPrimaryKey(Integer id);
	List<User> selectDetailsByUserId(String userid);
	List<User> selectDetailsList(String mywechatid);
	List<User> selectAlladdrByHost(String host);
    List<User> selectAllgroupsByHost(String host);
    List<User> selectDetailsMoments(String host);
	
}
